spring.application.name=smarthas-api
server.port=${PORT:8080}

# Oracle
spring.datasource.url=${ORACLE_URL:jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL}
spring.datasource.username=${ORACLE_USER:}
spring.datasource.password=${ORACLE_PASSWORD:}
spring.datasource.hikari.initialization-fail-timeout=-1
oracle.enabled=${ORACLE_ENABLED:false}